// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0uMb3YUuJNb_r_dt4r3vDmyDfc_fwSVI',
    appId: '1:552793619674:ios:5679abf5ba35805c7ef9e3',
    messagingSenderId: '552793619674',
    projectId: 'mentora-eb66b',
    storageBucket: 'mentora-eb66b.firebasestorage.app',
    iosBundleId: 'com.example.mental',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD16-WpmjtAA1_kMDVXbokfbtcxTc2q_VQ',
    appId: '1:552793619674:web:7504f45ac18f64d17ef9e3',
    messagingSenderId: '552793619674',
    projectId: 'mentora-eb66b',
    authDomain: 'mentora-eb66b.firebaseapp.com',
    storageBucket: 'mentora-eb66b.firebasestorage.app',
    measurementId: 'G-0X2VK733SJ',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD16-WpmjtAA1_kMDVXbokfbtcxTc2q_VQ',
    appId: '1:552793619674:web:96cb6c33d45cbf117ef9e3',
    messagingSenderId: '552793619674',
    projectId: 'mentora-eb66b',
    authDomain: 'mentora-eb66b.firebaseapp.com',
    storageBucket: 'mentora-eb66b.firebasestorage.app',
    measurementId: 'G-MHY2EQ2WSV',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0uMb3YUuJNb_r_dt4r3vDmyDfc_fwSVI',
    appId: '1:552793619674:ios:5679abf5ba35805c7ef9e3',
    messagingSenderId: '552793619674',
    projectId: 'mentora-eb66b',
    storageBucket: 'mentora-eb66b.firebasestorage.app',
    iosBundleId: 'com.example.mental',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArlKKl9Qo2wA_O9nwWtAhLPmHegylHa-k',
    appId: '1:552793619674:android:2d115edf1a2bcee07ef9e3',
    messagingSenderId: '552793619674',
    projectId: 'mentora-eb66b',
    storageBucket: 'mentora-eb66b.firebasestorage.app',
  );

}